spring:
    datasource:
        driverClassName : com.mysql.jdbc.Driver
        url : jdbc:mysql://120.78.211.181:3306/xiangxing?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnectForPools=true
        username : root
        password : 123456
        type : com.alibaba.druid.pool.DruidDataSource
        
    resources:
        static-locations : classpath:/templates/

    freemarker:
        request-context-attribute : request

server:
    port : 80

#文件上传路径
upload_file_path: d:/workspace/xiangxing/

#系统地址
sys_url: http://localhost:80/

#支付宝
Alipay.APP_ID: 2016080300154740
#Alipay.SERVER_URL: https://openapi.alipay.com/gateway.do
Alipay.SERVER_URL: https://openapi.alipaydev.com/gateway.do
Alipay.APP_PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCOxpnuvWrTVO3DTDCOfphEjiD+OjVY4O8EUStLjlNX8zIDRLbEAdDgZlwdvilB/jopyZISyy7BiNPnPPKtGLKofpbboyH9jbBeTvPLjArvQEQxtHVqcZPuGSfYgaQcgz9MT4aOIErFlpFbv/uvVE9XqX50V/plMpS2nPtHBOblUB5HHuSrwJ5KEC6akk2zoXYlN1Uly8ztr02KAA2qDRff8yRBInnTrwTq7wuVG6EwsyX2TFQSpK3tPiGaoGUk4kfAR/0U+LpBLW5ReJIfUq3I7yyGj3tuBJ4JqZnCaDal84BMqOCMW1OiLxyjDG/vxSyEBU8zBHDKPtxsBuyeeXvtAgMBAAECggEAWkU/Ni8Ux6E+4ufdG3r3EwE54wMyj4tIE9auJQtLrqPYzzA2zh7HzdlqDHQa6dqvM5R6gt9sJHk6YU2rsb2X1+iRwTSXXRSkmjwY8G0OzM45T6PlSPOesD+/bagp9s0UzE7LqDjKjbrxFK2BmA0aTTag+TZW3nzogb0nMnPq+Lh/d+0yxVx09ACfN/41mJH1OUHWaQXHDRwVk7AgiF73EUgXlkP8Bmi9Xy3gZX7qFbjX2WZvUXec2dyHjPloqlN1g0u0oaLMAnmX31jpP/Zw7zc0uaOkjgkcr1B7a59RS5wErCGu7L8v31Q+DJknK/qF001Lsbovjp7zBi2HCP1BkQKBgQD+djk14jqm33oNhJmcCdag5pa58RjyW6mL7DJsy7ID1I0KLQW99MJ6dfwe6Qm9TIuJOtj0XTwZCJg9a3M29ZBeCG2HIv/6u6ywMRqAovN5Hv2YFW8uy2f1+Ea4tNn3HmwmQrBRv/gcjEXtIJiTtZWvrUdGRyonoRC/5MzRDRAydwKBgQCPo4uJ2bcIJOL3V5M888Kw/uxtXuHbauH685h4QymU/pP8+h30kmiNE68XKEfdleVY9LI2zz1xhR/dc/7obBaHcWoRO3JGi1/o2VzaiznolmtwZ8hO5f5UVpmAktCfAGppSSv3XjRuFKyuG61LVD8+R4l6FljbW1s6E+nh5cEZuwKBgQDbTcSsvdbSrtOgBuHka05AybqpcjKP3ZPX9a7XuQ4o4uzTEk5akjFyHXE2qp0sOmYf1UnaAOikopWiiZJ4kVbk09qhlvaKf2irSQaQSuAPSThB9GcoK0Hj6R/6XFNl+SA4MU2IhywsXnB9l5Qn6V2iVHKTDQ41rUikOWqT2PBWrQKBgBoi4yAZOoHD3HyvNb5wiGuWZ0Tbb/Nx9l6odoTji6xtylXM2SiIf3e0LjbjgHgkb1AJbmgku4Rtecfc9HQsPsk0bN1n2LpXYANJkei+TrIwtKoGaF9a4DVOcK4BiO51r+cqhlKDlLy3DFi99oFvefaGI9DQQijf7bCasQMGwGVDAoGBAMTzXY2rMNVFjeatlzhbpOWiRC67ITLqsxDg2AHWikWywJyfRnAOVFQ6v90CouSS2z97181BWfJiTGbvHPslwUvHBP4FIkpbYD2yJiB9zpWpFT3WBu/xr1yBl1rCyBc4sEakubTUfX9M7KEqB6Cyib6vYwANsVYpCyM5CMHfZDq6
Alipay.ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjsaZ7r1q01Ttw0wwjn6YRI4g/jo1WODvBFErS45TV/MyA0S2xAHQ4GZcHb4pQf46KcmSEssuwYjT5zzyrRiyqH6W26Mh/Y2wXk7zy4wK70BEMbR1anGT7hkn2IGkHIM/TE+GjiBKxZaRW7/7r1RPV6l+dFf6ZTKUtpz7RwTm5VAeRx7kq8CeShAumpJNs6F2JTdVJcvM7a9NigANqg0X3/MkQSJ5068E6u8LlRuhMLMl9kxUEqSt7T4hmqBlJOJHwEf9FPi6QS1uUXiSH1KtyO8sho97bgSeCamZwmg2pfOATKjgjFtToi8cowxv78UshAVPMwRwyj7cbAbsnnl77QIDAQAB


