spring:
    datasource:
        driverClassName : com.mysql.jdbc.Driver
        url : jdbc:mysql://120.78.211.181:3306/xiangxing?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnectForPools=true
        username : root
        password : 123456
        type : com.alibaba.druid.pool.DruidDataSource
        
    resources:
        static-locations : classpath:/templates/

    freemarker:
        request-context-attribute : request
#mybatis:
#    type-aliases-package: com.classroom.common.model
#    mapper-locations : classpath:mapper/*.xml
