spring:
    datasource:
        driverClassName : com.mysql.jdbc.Driver
        url : jdbc:mysql://120.78.211.181:3306/xiangxing?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnectForPools=true
        username : root
        password : 123456
        type : com.alibaba.druid.pool.DruidDataSource
        
    resources:
        static-locations : classpath:/templates/

    freemarker:
        request-context-attribute : request

server:
    port : 80

#文件上传路径
#upload_file_path: d:/workspace/xiangxing/
upload_file_path: /data/xiangxing/uploadFile

#系统地址
sys_url: http://localhost:80/

#支付宝
#Alipay.APP_ID: 2018050960089142
#Alipay.SERVER_URL: https://openapi.alipay.com/gateway.do
#Alipay.APP_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCTwWHOANPdGqbHWaJBkGDdeSyEmVvq/F0qqc6I3r4plXr6qkFBzCmCdfEZFfMrflCtxCtMdzcJbuIJZezt1mLNsZu0qoi3dK40fLlqDsaNT3dx4cO8uDlaPq3/BXGjT6k6KfQwZf2l6iwT9xFXzdIv/cGmOdRzPEE+jLk5gm3SYpMrBeAYxqIs5gz5brjWkAFBMoOGPWWmMirLwkX4Nzb1NKWs9Isw9PfnZ5SalgLIsSHJCH1SoCuoQx4cVo9P4VPfrfdsJkGmZ04AaJxR27TQD2Ag7Ta+1s98U2cKECFEkvisrx22NAeq30MeqwezkT+fEfVHu3jCNQlx4Ubepz2dAgMBAAECggEAVintqT5eTpAeNh6VOnrBoiXpyiHMsoocoqaHpNWQO5vKLadfislOY5/3y1M7jV+KGOtO/LaAx+V7t1NTCZd94snyLTdNpv5KIJ2jWq/nJbzzwNuRU9pyx6fJu/Amxr/Lxfl1R0wS0NBwh+wKlxOVwRrP9OnAdLrsqVdTJLBk7sxcI/if5kLsEWGBHz52Sct3l+nXNsZlp6Bd+L/niSdycAbw8KZJsG2q76sfcnW7YuqWACFuHVp+jqqSPzIty95rNZqVK10+nP8wT3Ucage3q8NRF4omqQ/4UWThrlJo3xUkI4Nz5SxNSk87CwdJzXj6KBTc2iZHlKdR1UJT523KgQKBgQDgwXQE+22uCyQK6CljjQp6VGmUB50wqizfDCWdgzxX1rRzIAtoUsHD6slS3PiSnGJfTTjlyaOL8FQ2EhTnjojozAW/2rl/QEzTXULD7X00s0mgAQSeuD1VLVQo5rUYMmsF9gDlwX/ObErWzgrpIggesCgSj//cG40AJcyWa6KLMQKBgQCoS6m0ANw9h/Oj1EOzrfWRnqiMPy5YLYIoMv/pyUQnqp9TQTy3fNKhLOZkKPFGzKCwRcWcEkX/uc0dDYksn+s6FZ1LILbsoy5PnaHY4U6dIibATnRH/5a44EOjxZPDVJdBETgTbpLZWIoSWn8oW0KHo8Al8xmbGqdL1dpMT0OmLQKBgQCPc0m+qE9fx2KQx48rJ+kpHNlqDtYIKoWLMzCK8SlBkxsHY8uEIVXk2uT2S20n/kJXO212VJVbCuBkxnOrO3EszJNa2ZqNmpeuTBcCAIFqcogqZJvzRfp3dAAEPwQU1pEyc8os2qzdLocxxL54AC2YkKxy9I/Eh50eHAIRe8958QKBgCiJoST0mBhSKQOrW2tqWZ5r4xl1Foqy24knT7FWg44ycRIywpdH/8xG7m/t1MBDBemvxLulQysn7Bo1andPRe/FyQ+Rn748SClxRMzi6Ha9BSyJOUUmcX2yt1g5fTAtrglERoeXuNOVmhx1o+9qnAnkDaKWffJ4ZxfDOUPsS9U5AoGAGObQ4zXVaRKlRyvEud2jk9AQBhQXBHy7B3LokFK6VF98Vwbr2eEv2G0qpLi79sVbBfh3443sPZOdwJBl616jlew64wxuy0lYkKl44aYcNIXWpr3+y5XHznKTE9Nvxmo4q9PW9O3e6DKAPDvP4z3nxFGqSr+lisxpYwUl1quDCh0=
#Alipay.ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArd1xVnChH10KgINRQDd8nPXNLHr6JXw6ln31dyclrM5NuWWeiAbYcYRCzor9Gk6fZmbCIM3IZBvsBiEtpwAEM5SR29KvPn4jGiu7uTjAw5bsRSwuKsJ5XCLu4rtJ6CZPKsrC67xpMUb4eB5uel56fnvo0M6wfOCBHuiTx6cd99fymgDNZQNWpxo4GOFLILWD4u3fT1VbNM9IJkL7Q/UahLmWJ853AmDCYCJb9/Fe23JbsqArqET5gjMRk45m1Ki02AbZFGM0LfjQaq+89+v8U942AA110qckNhvREWtreERtDGwZ3gbSUADdzQoUYzKVgJ/gRaaWJn/NC3B72qn0AQIDAQAB

Alipay.APP_ID: 2016091800539376
Alipay.SERVER_URL: https://openapi.alipaydev.com/gateway.do
Alipay.APP_PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwJSyJm3LiArJLLIvP/PiX6LiXE+81nkwIb5oV2Iw1/9RiSFz+O4PBGoI7BMEZpXgwTKosJNzkFGuxjiLfmIJ9jfsWyBOZeW7cI5NRSDLFHMiJuZKnHQ+d2NG/8fWiaH2/WrgmXAil3BpWDaeWQ0awbhPNouCqBlbv/wczv87KD8uyVbseB0apQDohhzcmkb0q/YOc06T7aGkvclmVSeg50jL3a+aMC1bm5zHiwUDIy0JNF4aoSBsXghIEqw5asKIm9cm6ZO83pK9peBgX/RTgCQh3mYKF2Vc/aVwY9FptETX6lCELz2mYuBqZQYQsUuvuFsnpmwhJsa1mYP1UziYhAgMBAAECggEAcqA+U24tXJaUoAblFPxyaaiwNuBqEmJo6DR3+S9qTtmkxDCDE453NvqhNPbrEl1z0TqSoxd6B5KiYnE0kH0Wrc3vT+vzlTRIyEj+XS62mz8X4Ug5/zYSK44lMNusFXwaGKRYod3SYtzQ5p8MJ+Sv47A+gtsziHGHsbYsYai4URTQwlJ7THQIeT7Qv54aOEXMm/OWWv8STn7cbl+4mNULBJKehXu8lYqeYXofNxdhvbePmECQzVQ0oq9+90nQ1AuieTbC7rSKVXGnDoJ55eA5RMh44PDdd3Sod4rVJ45nkgxX/tPCmlSGKHFuhb3omAPuKSFol3xtRNP28a//VZSYgQKBgQDpe0Q7sG6nFoJdy9yHKSOwHiUj7p8J8U6X5UAM7M2PdTj/Ih4MKEGWohb34f/fmhqhR0VVwpptmCQMYegR4IoY9gB9T0t0OQE9Hix1MllhZRyjFwsUNysIBCgXL/H2oXNXfwXSWRW1sO6Atze/KXliHyD/jWWDIPXBVoUW+87+JQKBgQDBIkF8K0h+paqLVSU53jdTY/RClpg3povZkOgQrTS5bK+oYSz+irzn6NmicP0pKMaK7yd4USrbUPRFFC6+o5DdAb8Ch3utW1fVmcCpO9MOENWl6K96mUr0Wbp+eRlZX0H+HAUBu1/aPpBdw/+ZX1vtIi7gimAJyR3pDPvsdfpRTQKBgQCE/ADRPpzH7royUns5QOVi2sisvq03LIpnWdwxgG9U1p+wMe6LXiJ9ebU7Wy4yXcPtOHr1bfInmhBuPRXBmPMPZI7C0PdZK17ZQOZxmkvufXjiK63TxdhsqHFtQ5G9uBfKLj9SoAsNgclW5wSJjUXl7XUOGatIFO3lQTJs9N/hQQKBgQCvIALFNvI7dLkaMpDY0jjUstPv9WH9RFWXaKAlTwl6AaWeRs9n2CHHIAsIEvBb/A9cN9NQdDkqOVPlt5FTaDmZTVYIUxXAcg1JMGvUiNyt6nHwSPelcY7X1u0WdXSY55mNc5bOpTsbSJPbkjgYuLFAaziafp7rAKTQh+d/2NKsGQKBgADgEGvE8O1WTcTvcfFYPodGjAzTwqDlf4qWyMqE8Q3px7PKR+UFCDUrK9+YeyrqLLSWu/aBNHT85GzS51ZErd6RBTV3PLzl4zhc5+474JWr2LNAEqUeXi0tXhBrigeZaS6c5doU9ZdvcXQgJRSTi30pfYfbLynYl4cXaHqHogKC
Alipay.ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuC7L913QCK/PGnxMu+MwKNK6ftuIeAhlYgtuw8JJjDZ0FSMacLlkmUJLqiVN4f9924yJmFn5BX0qXqPE2oRoigmacKxz/KeyMRKG00z8CIcmUaEU1NJ0d5Jt2rQykH8tn3ZnlUflB5w87Dhc52xUKE9dMdRgyp2Ufx+Sw4vLOM0Dr/8s5KOcBEXxH2akmUHnxAe6/Ux9jiz72Zp2zouHJt63KAfrg310WFKQbK7Q/agYhLM9e7xtUsrj4CO9giuO70kYyh96Ogpt9bIL04LvgkJsJplfYfmkzlx7D/P2gSUhw72fRU/ePvKgm/xB9dotrAQWCYdecAoos+gAnPwIDAQAB






#微信支付
wechat_appId: wx7cf0ac001b331ca2
#商户号
wechat_mchID: 1503959681
wechat_key: 61a99775b3ac44209679e85183fd366c
#域名
wechat_domain: api.mch.weixin.qq.com


product_path:  /data/xiangxing/product/
homework_path:  /data/xiangxing/homework/
message_path:  /data/xiangxing/message/
pdf_path:  /data/xiangxing/pdf/

